FROM python:3.8

WORKDIR /code
COPY . /code

COPY docker/entrypoint.sh /code
RUN chmod a+x /code/entrypoint.sh

RUN pip install pipenv
RUN pipenv install --system --deploy --ignore-pipfile
RUN python ./setup.py install

EXPOSE 8000
CMD [ "/code/entrypoint.sh" ]
