"""
Django settings for demo project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import logging
import os

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

from response.slack.client import SlackClient

load_dotenv(verbose=True)

logger = logging.getLogger(__name__)

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "5m*pc(gb!k+!913@qh2u5z7^s-bbp2ytw28gdvcbly5ayw1i5+"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "adminlte3",
    "adminlte3_theme",
    "after_response",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_prometheus",
    "rest_framework",
    "response.apps.ResponseConfig",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
]

MIDDLEWARE = [
    "django_prometheus.middleware.PrometheusBeforeMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_prometheus.middleware.PrometheusAfterMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["response/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = "static"


# Django Rest Framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 100,
    # Use Django's standard `django.contrib.auth` permissions.
    # Change to IsAuthenticatedOrReadOnly for read-only unauthenticated access
    # or see the Django Rest Framework docs for more options:
    # https://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

# Markdown Filter

MARKDOWN_FILTER_WHITELIST_TAGS = [
    "a",
    "p",
    "code",
    "h1",
    "h2",
    "ul",
    "li",
    "strong",
    "em",
    "img",
]

MARKDOWN_FILTER_WHITELIST_ATTRIBUTES = ["src", "style"]

MARKDOWN_FILTER_WHITELIST_STYLES = [
    "width",
    "height",
    "border-color",
    "background-color",
    "white-space",
    "vertical-align",
    "text-align",
    "border-style",
    "border-width",
    "float",
    "margin",
    "margin-bottom",
    "margin-left",
    "margin-right",
    "margin-top",
]


def get_env_var(setting, warn_only=False):
    value = os.getenv(setting, None)

    if not value:
        error_msg = f"ImproperlyConfigured: Set {setting} environment variable"
        if warn_only:
            logger.warn(error_msg)
        else:
            raise ImproperlyConfigured(error_msg)
    else:
        value = value.replace('"', "")  # remove start/end quotes

    return value


SLACK_TOKEN = get_env_var("SLACK_TOKEN")
SLACK_CLIENT = SlackClient(SLACK_TOKEN)
SLACK_SLASH_COMMAND = "incident"

# Whether to use https://pypi.org/project/bleach/ to strip potentially dangerous
# HTML input in string fields
RESPONSE_SANITIZE_USER_INPUT = True

ZOOM_API_KEY = get_env_var("ZOOM_API_KEY")
ZOOM_API_SECRET = get_env_var("ZOOM_API_SECRET")
ZOOM_API_USER_ID = get_env_var("ZOOM_API_USER_ID")

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 2
LOGIN_REDIRECT_URL = "/"
LOGIN_URL = "/accounts/login"

GOOGLE_CLIENT_ID = get_env_var("GOOGLE_CLIENT_ID", True)
GOOGLE_CLIENT_SECRET = get_env_var("GOOGLE_CLIENT_SECRET", True)
GOOGLE_HOSTED_DOMAIN = get_env_var("GOOGLE_HOSTED_DOMAIN", True)

GITHUB_CLIENT_ID = get_env_var("GITHUB_CLIENT_ID", True)
GITHUB_CLIENT_SECRET = get_env_var("GITHUB_CLIENT_SECRET", True)

EXPORT_CONFLUENCE = True
CONFLUENCE_URL = get_env_var("CONFLUENCE_URL", True)
CONFLUENCE_USER = get_env_var("CONFLUENCE_USER", True)
CONFLUENCE_TOKEN = get_env_var("CONFLUENCE_TOKEN", True)
CONFLUENCE_SPACE = get_env_var("CONFLUENCE_SPACE", True)
CONFLUENCE_PARENT = get_env_var("CONFLUENCE_PARENT", True)

SOCIALACCOUNT_PROVIDERS = {}

if GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS["github"] = {
        "SCOPE": [
            "user",
            "repo",
            "read:org",
        ],
        "APP": {"client_id": GITHUB_CLIENT_ID, "secret": GITHUB_CLIENT_SECRET},
    }

if GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET:
    SOCIALACCOUNT_PROVIDERS["google"] = {
        "APP": {
            "client_id": GOOGLE_CLIENT_ID,
            "secret": GOOGLE_CLIENT_SECRET,
            "key": "",
        },
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {"access_type": "online"},
    }

    if GOOGLE_HOSTED_DOMAIN:
        SOCIALACCOUNT_PROVIDERS["google"]["AUTH_PARAMS"]["hd"] = GOOGLE_HOSTED_DOMAIN

if SOCIALACCOUNT_PROVIDERS != None:
    for provider in SOCIALACCOUNT_PROVIDERS.keys():
        INSTALLED_APPS.append("allauth.socialaccount.providers.%s" % provider)
