# Generated by Django 3.1.1 on 2020-10-18 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0017_incident_zoom_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='zoom_meeting',
        ),
    ]
