# Generated by Django 3.1.1 on 2020-10-25 04:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0017_incident_mitigated'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='mitigated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now, help_text='Time of when this update was added.')),
                ('text', models.TextField(help_text='Freeform text to provide status')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='response.externaluser')),
            ],
        ),
    ]
