# Generated by Django 3.1.1 on 2020-10-26 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("response", "0020_headlinepost_zoom_meeting"),
        ("response", "0018_auto_20201025_0441"),
    ]

    operations = []
