# Generated by Django 3.1.1 on 2020-11-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("response", "0021_merge_20201026_0357"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="post_mortem",
            field=models.URLField(blank=True, null=True),
        ),
    ]
